Design and Analysis of Algorithms Assignment-2: SegLeast.cpp File Reference
SegLeast.cpp File Reference
#include <bits/stdc++.h>
Data Structures
struct Point
Macros
#define LIMIT_VAL 10000
#define infi numeric_limits<double>::infinity()
Definiton of Point data structure.
Functions
vector< double > X (10000+1)
vector< double > Y (10000+1)
vector< double > XY (10000+1)
vector< double > X_sqr (10000+1)
vector< double > optimum (10000+1)
vector< double > seg_opti (10000+1)
vector< vector< double > > slope (10000+1, vector< double >(10000+1))
vector< vector< double > > intercept (10000+1, vector< double >(10000+1))
vector< vector< double > > error (10000+1, vector< double >(10000+1))
helper function to initialize values
void init ()
helper function to update values in X, Y, Xy and X_sqr
void XYInitializer (int i, int j)
helper function to updare sum_x, sum_y, sum_xy, sum_x_sqr
void sumInitializer (int i, int j)
driver code
int main ()
Variables
stack< int > seg
struct Point pts [10000+1]
int num
int i = 1
int j = 1
int k = 1
int gap
double sum_x
double sum_y
double sum_xy
double sum_x_sqr
double numr
double denr
double temp
double mini
double C
Macro Definition Documentation
infi
#define infi numeric_limits<double>::infinity()
Definiton of Point data structure.
Definition at line 34 of file SegLeast.cpp.
Referenced by main().
LIMIT_VAL
#define LIMIT_VAL 10000
Definition at line 33 of file SegLeast.cpp.
Function Documentation
error()
vector<vector<double> > error (10000+ 1, vector< double > 10000+1)
helper function to initialize values
Referenced by main().
init()
void init ()
helper function to update values in X, Y, Xy and X_sqr
Definition at line 60 of file SegLeast.cpp.
References X(), X_sqr(), XY(), and Y().
Referenced by main().
intercept()
vector<vector<double> > intercept (10000+ 1, vector< double > 10000+1)
Referenced by main().
main()
int main ()
< Input through script
<Manual input
< Sort points
Definition at line 101 of file SegLeast.cpp.
References C, denr, error(), gap, i, infi, init(), intercept(), j, k, mini, num, numr, optimum(), pts, seg_opti(), slope(), sum_x, sum_x_sqr, sum_xy, sum_y, sumInitializer(), temp, visualization::x, Point::x, XYInitializer(), visualization::y, and Point::y.
 {
     cout << "Enter 1 for manual input, 2 to run input script\n";
     int inp;
     cin >> inp;
     ifstream ip;
     ofstream opp;
     if (inp == 2)
     {
         ip.open("points.txt");
         ip >> num;
         cout << num << " points:" << endl;
         while (i <= num)
         {
             ip >> pts[i].x >> pts[i].y;
             i++;
         }
         i = 1;
         while (i <= num)
         {
             cout << pts[i].x << " " << pts[i].y << endl;
             i++;
         }
     }
     else
     {
         opp.open("points.txt");
         double x, y;
         cout << "Enter the number of points : ";
         cin >> num;
         opp << num << endl;
         cout << "Enter " << num << " points :" << endl;
         for (int i = 1; i <= num; i++)
         {
             cin >> x >> y;
             pts[i].x = x;
             pts[i].y = y;
             opp << x << " " << y << endl;
         }
     }
     cout << "Enter the cost of creating a new segment : ";
     cin >> C;
     sort(pts + 1, pts + num + 1);
     init();
     j = 1;
     while (j <= num)
     {
         XYInitializer(i, j);
         i = 1;
         while (i <= j)
         {
             gap = j - i + 1;
             sumInitializer(i, j);
             numr = gap * sum_xy - sum_x * sum_y;
             (numr != 0) ? (denr = gap * sum_x_sqr - sum_x * sum_x,
                                          (denr != 0) ? slope[i][j] = (numr / double(denr)) : slope[i][j] == infi)
                                     : (slope[i][j] = 0.0);
             intercept[i][j] = (sum_y - slope[i][j] * sum_x) / double(gap);
             k = i;
             error[i][j] = 0.0;
             while (k <= j)
             {
                 temp = pts[k].y;
                 temp -= slope[i][j] * pts[k].x;
                 temp -= intercept[i][j];
                 double val = temp;
                 val *= temp;
                 error[i][j] += val;
                 k++;
             }
             i++;
         }
         j++;
     }
     optimum[0] = 0;
     seg_opti[0] = 0;
     j = 1;
     while (j <= num)
     {
         i = 1;
         mini = infi;
         k = 0;
         while (i <= j)
         {
             temp = error[i][j] + optimum[i - 1];
             (temp < mini) ? (mini = temp, k = i) : 0;
             i++;
         }
         optimum[j] = mini + C;
         seg_opti[j] = k;
         j++;
     }
     ofstream title;
     title.open("title.txt");
     cout << endl
              << "The cost of the optimal solution : " << optimum[num] << endl;
     title << endl
                 << "The cost of the optimal solution : " << optimum[num] << endl;
     i = num;
     j = seg_opti[num];
     while (i > 0)
     {
         seg.push(i);
         seg.push(j);
         i = j - 1;
         j = seg_opti[i];
     }
     ofstream op;
     op.open("segments.txt");
     cout << endl
              << "An optimal solution is:" << endl;
     for (; !seg.empty();)
     {
         i = seg.top();
         seg.pop();
         j = seg.top();
         seg.pop();
         cout << "Segment (y = " << slope[i][j] << " * x + " << intercept[i][j]
                  << ") from points " << i << " to " << j
                  << " with square error " << error[i][j] << endl;
         op << pts[i].x << " " << pts[i].y << " " << pts[j].x << " " << pts[j].y << endl;
     }
     return 0;
 }
optimum()
vector<double> optimum (10000+ 1)
Referenced by main().
seg_opti()
vector<double> seg_opti (10000+ 1)
Referenced by main().
slope()
vector<vector<double> > slope (10000+ 1, vector< double > 10000+1)
Referenced by main().
sumInitializer()
void sumInitializer (int i, int j)
driver code
Definition at line 85 of file SegLeast.cpp.
References j, sum_x, sum_x_sqr, sum_xy, sum_y, X(), X_sqr(), XY(), and Y().
Referenced by main().
X()
vector<double> X (10000+ 1)
Referenced by init(), sumInitializer(), and XYInitializer().
X_sqr()
vector<double> X_sqr (10000+ 1)
Referenced by init(), sumInitializer(), and XYInitializer().
XY()
vector<double> XY (10000+ 1)
Referenced by init(), sumInitializer(), and XYInitializer().
XYInitializer()
void XYInitializer (int i, int j)
helper function to updare sum_x, sum_y, sum_xy, sum_x_sqr
Definition at line 69 of file SegLeast.cpp.
References j, pts, Point::x, X(), X_sqr(), XY(), Point::y, and Y().
Referenced by main().
Y()
vector<double> Y (10000+ 1)
Referenced by init(), sumInitializer(), and XYInitializer().
Variable Documentation
C
double C
Definition at line 50 of file SegLeast.cpp.
Referenced by main().
denr
double denr
Definition at line 50 of file SegLeast.cpp.
Referenced by main().
gap
int gap
Definition at line 49 of file SegLeast.cpp.
Referenced by main().
i
int i = 1
Definition at line 49 of file SegLeast.cpp.
Referenced by main().
j
int j = 1
Definition at line 49 of file SegLeast.cpp.
Referenced by main(), sumInitializer(), and XYInitializer().
k
int k = 1
Definition at line 49 of file SegLeast.cpp.
Referenced by main().
mini
double mini
Definition at line 50 of file SegLeast.cpp.
Referenced by main().
num
int num
Definition at line 49 of file SegLeast.cpp.
Referenced by main().
numr
double numr
Definition at line 50 of file SegLeast.cpp.
Referenced by main().
pts
struct Point pts[10000+1]
Definition at line 48 of file SegLeast.cpp.
Referenced by main(), and XYInitializer().
seg
stack<int> seg
Definition at line 47 of file SegLeast.cpp.
sum_x
double sum_x
Definition at line 50 of file SegLeast.cpp.
Referenced by main(), and sumInitializer().
sum_x_sqr
double sum_x_sqr
Definition at line 50 of file SegLeast.cpp.
Referenced by main(), and sumInitializer().
sum_xy
double sum_xy
Definition at line 50 of file SegLeast.cpp.
Referenced by main(), and sumInitializer().
sum_y
double sum_y
Definition at line 50 of file SegLeast.cpp.
Referenced by main(), and sumInitializer().
temp
double temp
Definition at line 50 of file SegLeast.cpp.
Referenced by main().